Add a loading spinner for TryExamples directive.
jupyterlite/jupyterlite-sphinx pull request #133
Opened 2024-01-31 17:31 UTC by steppi

This PR adds a loading spinner for the TryExamples directive. I've offered no options to customize the spinner because I don't have sufficient time to think about how to do that cleanly and document it properly. My goal is just to get this working before submitting a PR adding interactive docs to SciPy. We can revisit later.

I've also fixed a bug where I was referring to a configuration variable which no longer exists (it only occurs when `global_enable_try_examples = True`), and I've added a link to `try_examples.css` in the try examples documentation to make it easier for readers to find that file.

2024-02-01 02:25 UTC, steppi commented
I've deployed SciPy's docs built against this feature branch. You can check out the spinner in action here https://steppi.github.io/scipy/reference/generated/scipy.stats.kurtosistest.html#scipy.stats.kurtosistest

2024-02-01 08:29 UTC, martinRenou requested changes
I tried the link you pointed to, looks great!!

It seems the spinner is not centered on the iframe, which is odd given the CSS you apply (absolute positioning + width 50% and height 50%), not sure what's wrong.

2024-02-01 08:29 UTC, martinRenou commented on jupyterlite_sphinx/jupyterlite_sphinx.css
> +.try_examples_spinner {
It would be nice to generalize this across jupyterlite-sphinx. For example, having this spinner show up instead of the "Loading..." message when clicking on "Try JupyterLite" here: https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/jupyterlite.html

2024-02-01 15:19 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.js
> +              spinner.style.top = `${spinnerTop}px`;
> It seems the spinner is not centered on the iframe, which is odd given the CSS you apply (absolute positioning + width 50% and height 50%), not sure what's wrong.

The spinner position gets set in the javascript here. I put it closer to the top because a lot of SciPy's examples are very long, and a centered spinner usually isn't visible when the button is still in view in those cases. I guess it would make more sense to set it to be 50% unless this ends up out of the viewport, and otherwise put just close enough to the top to be in view.

2024-02-01 22:00 UTC, steppi commented
SciPy docs incorporating the updates are up now: https://steppi.github.io/scipy/reference/generated/scipy.stats.kurtosistest.html#scipy.stats.kurtosistest

2024-02-02 08:25 UTC, martinRenou approved these changes
Thanks!

2024-02-02 08:26 UTC, merged