Use `try_examples_global_button_text` if provided for `TryExamples` directive
jupyterlite/jupyterlite-sphinx pull request #161
Opened 2024-03-29 12:09 UTC by agriyakhetarpal

## Description

This PR updates the `TryExamplesDirective` class to use the configuration value in `conf.py` if specified, and otherwise use the "Try it with JupyterLite" text. This way, buttons that are created manually with the

```rst
.. try_examples::
```

directive in Sphinx will receive the same configuration value, and adding a `:button_text` input across several `.. try_examples::` directives to customise the button text will now **not** be required. The `try_examples_global_button_text` string will be used by default, instead of the current `"Try it with JupyterLite!"` text.

To explain this behaviour, an additional sentence has been added to the documentation for the `TryExamples` directive page.

Closes #157 

## Footnotes

This is essentially a breaking change of sorts for dependents who are not using a custom `:button_text` input already, since it will now change the text to what they have set in `try_examples_global_button_text` (in case they have set that). But it's surely not a very big change and I would consider it as more of an enhancement (cc: @steppi)

2024-03-29 12:12 UTC, agriyakhetarpal commented
Happy to add a CHANGELOG entry for this if needed!

2024-03-29 12:25 UTC, agriyakhetarpal commented
Oops, let me run `black` and rebase

2024-03-29 12:25 UTC, steppi commented
> Happy to add a CHANGELOG entry for this if needed!

No need! The change log gets autogenerated by the prep release GitHub workflow.

2024-03-29 13:15 UTC, steppi commented
Thanks @agriyakhetarpal! Looking good so far. One thing: I think that all of the global config options should be propagated if a custom option isn't given, not just  `try_examples_globalbutton text`. You should also do `try_examples_global_theme`, and `try_examples_global_warning_text`.

2024-03-29 13:22 UTC, agriyakhetarpal commented
Right, I had thought of doing `try_examples_global_warning_text` too, but that would become a bigger breaking change, wouldn't it? People will have to override the global warning text and set it to `None` if they are using manual `TryExamples` directives somewhere. It does make sense, but I guess you're more aware of how downstream users would react, though. 

I agree about `try_examples_global_theme`, however – I'll make that change and for the other global config options.

2024-03-29 14:21 UTC, agriyakhetarpal commented
Fair point, didn't consider that the directive was/is still experimental – I have added in the requested changes! Now, one should be able to use the global warning text and use the global name for the theme/CSS container styling.

2024-03-30 02:51 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            button_text = self.options.pop("button_text", "Try it with JupyterLite!")
```suggestion
        default_button_text = self.env.config.try_examples_global_button_text
        if default_button_text  is None:
            default_button_text = "Try it with JupyterLite!"
        button_text = self.options.pop("button_text", default_button_text)
```

Two things. The use of `pop` instead of `get` is essential. We don't want "button_text" to remain in the `self.options` dictionary. The remaining key value pairs will passed as options into a url later on.

Second, I think the way I've suggested is cleaner because the control flow logic is used explicitly used to determine the default button text, and we avoid duplicating the logic to pop something from the dictionary.

2024-03-30 09:09 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            button_text = self.options.pop("button_text", "Try it with JupyterLite!")
Thanks! I had an issue come up where the button disappeared completely when I had used `pop` to display a global warning, I'm not sure why – so I had replaced everything with `get` instead.

I'm not sure why that happened, let me try to debug that.

2024-03-30 10:15 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            button_text = self.options.pop("button_text", "Try it with JupyterLite!")
Your logic was much better, and everything works as expected – tested all of them again. Addressed in 47621ff2dc743ca4491046bc97b9c04009e1291e.

2024-03-30 14:35 UTC, steppi requested changes
Thanks @agriyakhetarpal. This is looking better. A few minor suggestions.

2024-03-30 14:35 UTC, steppi commented on docs/directives/try_examples.md
> +* `:warning_text:` Prepend a markdown cell to the notebook containing this text, styled to make it clear this is intended as a warning. The default value is the value of the global configuration vari
I think it makes more sense for you not to change these, and then mention that `try_examples_global` config options apply both to automatically inserted `try_examples` directives, and manually inserted ones when the global configuration is discussed. For instance, I wouldn't consider the value of `try_examples_global_warning_text` to be a default, I think of it as setting to a non-default value in the global config. Also, I think it's better not to refer so heavily to the `try_examples_global` config options before they are introduced.

2024-03-30 14:35 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        warning_text = self.options.pop("warning_text", default_warning_text)
The current default is for there to be no warning cell. I think we should keep that.

2024-03-30 14:41 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +                    "`jupyterlite build` failed but its output has been silenced."
Thank you for the advice. I will make a note of this in future PRs.

2024-03-30 14:56 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        warning_text = self.options.pop("warning_text", default_warning_text)
That makes sense – I reverted the change in 958b12e3697f747b54abaaf2b09990a8bf84ea4f. It should now pick up `self.env.config.try_examples_global_warning_text`, which can either be set to a string or it can be `None`. Let me know if you want a more stringent check.

2024-03-30 15:09 UTC, agriyakhetarpal commented on docs/directives/try_examples.md
> +* `:warning_text:` Prepend a markdown cell to the notebook containing this text, styled to make it clear this is intended as a warning. The default value is the value of the global configuration vari
I agree with all of the three points. I have included these details under the "Global Configuration" section and reverted two of my previous commits in 7dad6e20120067617c2213eaa34515943038e096, and these details do make more sense there.

2024-03-30 15:56 UTC, steppi commented on docs/directives/try_examples.md
> -There is no option to set a global specific height because the proper height
I'm not sure this is an improvement. It's distance from a contrasting statement makes the "However" seem out of place to me.

2024-03-30 15:58 UTC, agriyakhetarpal commented on docs/directives/try_examples.md
> -There is no option to set a global specific height because the proper height
Should we allow overriding the height – we don't do that currently?

2024-03-30 16:05 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        example_class = self.options.pop("example_class", default_example_class)
I don't think we need a specific comment like this for each config option. I think it's clear enough to have a single comment above the processing of options that says something like:

Use global configuration values from `conf.py` in manually inserted directives if they are provided and the user has not specified a config value in the directive itself.

Also I think it makes sense to make `height` either before or after all of the other instances, since it is treated differently. You can mention here there is no global option for height.

2024-03-30 16:09 UTC, agriyakhetarpal commented on docs/directives/try_examples.md
> -There is no option to set a global specific height because the proper height
I got confused with something else, please don't mind. Since we do have a method to set a global minimum height with the JSON file, I think removing "However" is okay – it makes it feel like there is a setback when there is none.

2024-03-30 16:09 UTC, agriyakhetarpal commented on docs/directives/try_examples.md
> -There is no option to set a global specific height because the proper height
Addressed this in 998cd260a78a8b337682116d8a87404b0f19cd0a

2024-03-30 16:16 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        example_class = self.options.pop("example_class", default_example_class)
Thanks, I added a single comment in 62b3dea0b88a27e4802c11f388e8be6e77eaeab4 for the applicable options, and added another comment above the `height` configuration to signify the difference between the rest

2024-03-30 17:13 UTC, steppi requested changes
Thanks @agriyakhetarpal. this is in good shape now. Just a couple minor suggestions on language.

2024-03-30 17:13 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        # manually in the directive.
Not technically true because of the min height option in `try_examples.json`.

I think just "A global height cannot be set in conf.py" is clear enough

2024-03-30 17:13 UTC, steppi commented on docs/directives/try_examples.md
> +inserted directive, which will override the global settings on a per-directive basis.
```suggestion
`try_examples_global_button_text`, `try_examples_global_theme`, and `try_examples_global_warning_text` in `conf.py`;
these apply both to automatically and manually inserted directives. Options set explicitly in a directive will
override the global configuration.
```

A semicolon should link two independent clauses which form a logical whole. The effect is to imply a pause of shorter duration than a hard stop. Starting the second clause with an "and" makes it a dependent clause. Also I think this can be expressed more concisely.

2024-03-30 17:27 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        # manually in the directive.
You're right. Addressed this in cd542e3c48ba2935881f13a8079f56e6c84a8009.

2024-03-30 17:46 UTC, steppi approved these changes
Thanks @agriyakhetarpal! This looks good now.

2024-03-30 17:46 UTC, merged