[WIP]: Pass additional configuration options to the `jupyter lite build` command
jupyterlite/jupyterlite-sphinx pull request #169
Opened 2024-04-29 15:59 UTC by agriyakhetarpal

## Description

This PR closes #168. It aims to implement additional options from the JupyterLite CLI, i.e., the `jupyter lite build` command that is currently wrapped in a subprocess call inside a Sphinx app. This enables the use of, say, custom environments from a file, allowing overrides in case of conflicts where `environment.yml` might refer to a file that is not being used for Sphinx.

## Changes made (so far)

- Added `--XeusAddon.environment_file` as a configuration value to allow users to specify a custom `environment.yml` file to specify their dependencies for pre-installation with the `jupyterlite-xeus` kernel.

## TODO

- [ ] Look at other options from https://jupyterlite.readthedocs.io/en/latest/reference/cli.html#common-parameters and see which ones we can further implement here
- [ ] Add documentation about `xeus_environment_file` and link to `conf.py` about this
- [ ] Add documentation about other user-configurable options (point 1)
- [ ] Some of the options are available to be overridden by environment variables, adjust the default values in the `setup()` function?
- [ ] Address potential conflicts with options, as noted by @steppi in #168, copying here for ease of access:

> except we might want to document how to avoid having options that conflict with the ones that are currently included, and put in place safeguards to prevent conflicting options

A list of options that should not cause any conflicts is as follows: `--lite-dir`, `--output-dir`, `--cache-dir`, `--contents`, and `--source-date-epoch`. The `--port` option can cause conflicts and should probably be restricted to where the Sphinx documentation is hosted, say, if someone is using `sphinx-autobuild` to build the docs and serve them. I'm not entirely sure about the use of `--ignore-sys-prefix` or `--federated-extensions` – and having `--settings-overrides` could also override a few options that a user can set manually. Besides some other addons, some addons are available to be configured (https://jupyterlite.readthedocs.io/en/latest/reference/cli.html#addon-configuration), which are specific in functionality to the addons and are not going to influence the JupyterLite build. I wonder if it would make sense for users to provide their custom `jupyter lite build --arg1 <...> --arg2 <...> --Addon.arg3 <...>` command which can be set by the user in `conf.py` and parsed by the extension to be passed to this subprocess? This would allow for a higher level of customisation and flexibility, at their discretion which the extension would not be responsible for.

## Additional context

Since the `jupyterlite-pyodide` kernel doesn't support pre-installing packages right now, it's not possible to add `requirements.txt` files. Users shall have to use the `emscripten-forge` channel and the `xeus` kernel to get the packages they need.

2024-04-29 16:33 UTC, steppi commented
Thanks @agriyakhetarpal. Is there any reason why we can't just let the users pass a dictionary of options with values in `conf.py`, and check that none of the options they've provided conflict with the existing ones? To me, this seems preferable to manually adding new options every time we discover something that would make sense to have.

2024-04-29 16:42 UTC, agriyakhetarpal commented
> Thanks @agriyakhetarpal. Is there any reason why we can't just let the users pass a dictionary of options with values in `conf.py`, and check that none of the options they've provided conflict with the existing ones? To me, this seems preferable to manually adding new options every time we discover something that would make sense to have.

This is what I was thinking as well with allowing a custom `jupyter lite build` command – a dictionary would indeed serve that purpose better, sure. Do you have something in mind about checking for conflicts with existing options, i.e., do we plan to check against the current trio of `--contents`, `--output-dir`, and `--lite-dir` – and gracefully raise an error, and for _additional_ options that we currently don't have but plan to add with this PR, let the `jupyter lite` CLI raise errors on conflicts on its own accord?

2024-04-29 16:45 UTC, steppi commented
> Do you have something in mind about checking for conflicts with existing options, i.e., do we plan to check against the current trio of `--contents`, `--output-dir`, and `--lite-dir` – and gracefully raise an error, and for _additional_ options that we currently don't have but plan to add with this PR, let the `jupyter lite` CLI raise errors on conflicts on its own accord?

Yeah, checking for conflicts with the existing options, and if found raising, but leaving anything beyond that to the  `jupyter lite` CLI sounds like the right approach. When we document this, we can show what the default command is and let users know there will be an error if they supply options that conflict with that, but beyond that, they are responsible for entering sensible options.

2024-04-29 17:40 UTC, agriyakhetarpal commented
Thanks, here's a very crude implementation in a0328121625c909fa2333f1ff4dd53118d06c134, I feel that `snake_case` is better than `kebab-case`, especially inside Python files like it is so here. I think it needs further refinement, and additions to the documentation of course. Open to suggestions.

2024-04-29 17:43 UTC, agriyakhetarpal commented
Thanks, here's a very crude implementation in 6eb6680664cb5096fba50d1a7e446409533197cd – I feel that `snake_case` is better than `kebab-case`, especially inside Python files like it is so here. I think it needs further refinement, and additions to the documentation of course. Open to suggestions.

Also, I un-silenced JupyterLite in 617a614831fd850b3462a320bd7d09f911bb413f, maybe it's good for us because we can inspect the logs both when checks pass and when they don't? Happy to revert the change if you disagree!

2024-04-29 17:56 UTC, steppi commented
Thanks @agriyakhetarpal. This is starting to look good. I'll take a closer look later today.

> Also, I un-silenced JupyterLite in [617a614](https://github.com/jupyterlite/jupyterlite-sphinx/commit/617a614831fd850b3462a320bd7d09f911bb413f), maybe it's good for us because we can inspect the logs both when checks pass and when they don't? Happy to revert the change if you disagree!

I see, what you've done is not to un-silence the output by default, but just override the default in the `conf.py` for `jupyterlite-sphinx`'s docs. We might want to do that, but if so it should go into a separate PR and be discussed separately.

Can you add the example from https://github.com/jupyterlite/jupyterlite-sphinx/issues/168#issuecomment-2079472156 for changing the path to where `xeus` looks for the environment file to the docs?

2024-04-29 18:00 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +                command.extend([f"--{key.replace('_', '-')}", value])
I think it's an unnecessary complication to try to let users pass in commands with snake case when the option flag is not snake case. Also, what about commands that really have underscores like

```
jupyter lite build --XeusAddon.environment_file=some_path/to/environment.yaml
```?

2024-04-29 18:01 UTC, agriyakhetarpal commented
> I see, what you've done is not to un-silence the output by default, but just override the default in the conf.py for jupyterlite-sphinx's docs. We might want to do that, but if so it should go into a separate PR and be discussed separately.

Ah, apologies if I was too terse. I indeed mean to do it for `jupyterlite-sphinx`, i.e., here, and not for other repositories. However, I agree that it should go into another PR, not here – I'll revert the commit.

2024-04-29 18:15 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +                command.extend([f"--{key.replace('_', '-')}", value])
You're right, it could definitely break things that way – we can ask people to type `kebab-case`, and silently changing to snake_case isn't ideal for user behaviour. Addressed this in 9f13354a53cc8d9b118e7ae595e7b535a354ba65.

2024-04-29 18:38 UTC, steppi commented on docs/configuration.md
If you want to clean up the formatting that would be better to do in a separate PR.

2024-04-29 18:58 UTC, agriyakhetarpal commented on docs/configuration.md
Reverted this in 511b5c6e7c692371d33c02496ce5703a24416fd7. I'll make a new PR with these changes later!

2024-04-29 18:59 UTC, agriyakhetarpal commented
> Can you add the example from https://github.com/jupyterlite/jupyterlite-sphinx/issues/168#issuecomment-2079472156 for changing the path to where xeus looks for the environment file to the docs?

I have now done this in f6e6d3b2154fe42b22528d3bb1b108ad04d3ab84, happy to receive comments on the wording and if the location of this section is alright. I enabled some admonitions for this page by enabling the `colon_fence` MyST extension in 0b5e4996648f7363774d2f10b531a6d020ee856f, please let me know if that is out of scope for this PR.

2024-04-29 19:57 UTC, steppi commented on docs/configuration.md
> +```
Have you tested this out. I got the error

```
Extension error (jupyterlite_sphinx.jupyterlite_sphinx):
Handler <function jupyterlite_build at 0x717566aa3010> for event 'build-finished' threw an exception (exception: Expected all commands arguments to be a str, got ['jupyter', 'lite', 'build', '--debug', '--contents', '/home/birbir/interactive_doc_experiments/doc/source/_contents', '--output-dir', '/home/birbir/interactive_doc_experiments/doc/build/html/lite', '--apps', 'notebooks', '--apps', 'edit', '--apps', 'lab', '--apps', 'repl', '--apps', 'tree', '--apps', 'consoles', '--apps', 'voici', '--lite-dir', '/home/birbir/interactive_doc_experiments/doc/source', '--port', 8888])
make: *** [Makefile:25: html] Error 2
```

because port is an `int` here, but `subprocess.run` expects all command args to be strings. If you want to be able to allow integers here, they need to be converted to strings.

Also, in this context, I don't think it makes any sense to specify a `port` here, so let's not use that in the example. It's lucky you included it though, because we might have missed the bug.

I think just having the `"XeussAddon.environment_file"` option is file here.

2024-04-29 19:59 UTC, steppi commented on docs/configuration.md
> +:::
I think all of these admonitions are drawing too much attention to what's supposed to be an advanced feature that will only be used by people who know what they're doing.

2024-04-29 20:04 UTC, agriyakhetarpal commented on docs/configuration.md
> +```
Addressed in d1acb8874c1d39f0bb70e13ca0a9b7da368492ee, I have now just kept the `"XeussAddon.environment_file"` option and clarified the sentence below it

2024-04-29 20:05 UTC, agriyakhetarpal commented on docs/configuration.md
> +:::
That makes sense, removed them in 6cc2cabe7ca868045f6a45707897e24b5f8f39e7 (we can look into adding the `colon_fence` plugin later)

2024-04-29 20:18 UTC, steppi commented on docs/configuration.md
> +
What do you think of this wording?

Additional arguments can be passed to the `jupyter lite build` command using the configuration
option `jupyterlite_build_command_options` in `conf.py`. The following example shows how to
specify an alternative location for the `xeus` kernel's `environment.yml` file as discussed
[here](https://github.com/jupyterlite/xeus?tab=readme-ov-file#usage).

```python
jupyterlite_build_command_options = {
    "XeusAddon.environment_file": "jupyterlite_environment.yml",
    }
```

This causes the additional option `--XeusAddon.environment_file=jupyterlite_environment.yml`
to be passed to `jupyter lite build` internally within `jupyterlite-sphinx`. Note that one
does not include the leading dashes, `--`, in the keys.

The options `--contents`, `--output-dir`, and `--lite-dir` cannot be passed to `jupyter lite build` in this way. These can instead be set with
the [`jupyterlite_contents`](#jupyterlite-content) and [`jupyterlite_dir`](#jupyterlite-dir) configuration options described above.

2024-04-29 20:19 UTC, agriyakhetarpal commented on docs/configuration.md
> +
This reads well to me. Thanks! Committing this change.

2024-04-29 20:22 UTC, steppi commented on docs/configuration.md
> +
and then I don't think the thing about the full list of commands should be included. It doesn't actually include the full list of commands, and the most useful ones will probably be for `Addons` which aren't included there.

2024-04-29 20:24 UTC, agriyakhetarpal commented on docs/configuration.md
> +
Should we point to some particular JupyterLite Addons just in case, while not being too verbose about it?

2024-04-29 20:27 UTC, steppi commented on docs/configuration.md
> +
I don't think so. I don't think we want to explicitly encourage people to use this, but it's good it's there in case someone needs it. I expect anyone who needs this level of customization will be able to figure things out from the info here.

2024-04-29 20:29 UTC, agriyakhetarpal commented on docs/configuration.md
> +
Thanks, addressed in 7b954c44f9724b8279c3ca0a6146cd3c70bc26f4.

2024-04-29 20:29 UTC, steppi commented on docs/configuration.md
> +
Maybe add a sentence like,

```
This is an advanced features and users are responsible for providing sensible command line options.
```

2024-04-29 20:31 UTC, agriyakhetarpal commented on docs/configuration.md
> +
Added the sentence in d49069ef7ab65494640c72ee2bcf578547524a6c.

2024-04-29 20:33 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +        )
Should we keep this as `[str, str]` since we're not pre-processing any of the values from the dict?
```suggestion
        jupyterlite_build_command_options: Dict[str, str] = (
            app.env.config.jupyterlite_build_command_options
        )
```

2024-04-29 21:03 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +                command.extend([f"--{key}", value])
```suggestion
                    raise ValueError(jupyterlite_command_error_message)
                command.extend([f"--{key}", str(value)])
```

I think it's fine just to convert these to `str` here, and then you can leave the `Any` in the type hints.

2024-04-30 01:35 UTC, steppi requested changes
A couple more suggestions for the exception raised when conflicting options are supplied.

2024-04-30 11:44 UTC, steppi commented
@agriyakhetarpal. Do you still consider this to be a work in progress, and if so, what else are you planning to do?

2024-04-30 11:45 UTC, agriyakhetarpal commented
I just merged `main` and I was editing the PR description just now :) I think this should be good to go very soon.

2024-04-30 12:10 UTC, agriyakhetarpal commented
Edited the title and the description. I think this is the only remaining point that we can think to address:

> Some of the options are available to be overridden by environment variables, adjust the default values in the `setup()` function?

If someone does not pass in a custom option via `conf.py` through this configuration value, they can alternatively do so using environment variables. However, it is possible that options set via environment variables can cause conflicts with those  set via `conf.py` and it would be difficult for the user to debug that? I don't see anything in the CLI documentation about whether the environment variable takes priority or whether the option in the command does (it is the latter, I just confirmed, and it's usually so based on how most CLIs work – but should we document that, considering we would like to reduce irrelevant bug reports?)

2024-04-30 12:21 UTC, steppi commented
> but should we document that, considering we would like to reduce irrelevant bug reports?)

Yes. I think it would be good to add a sentence saying that options in the `jupyter lite build` command take precedence over options in the config file. Before the sentence about this being an advanced feature I think.

2024-04-30 12:24 UTC, steppi commented
> Yes. I think it would be good to add a sentence saying that options in the `jupyter lite build` command take precedence over options in the config file. Before the sentence about this being an advanced feature I think.

Or I guess there are environment variables, a json config file, and command line options?

2024-04-30 12:31 UTC, agriyakhetarpal commented
> Or I guess there are environment variables, a json config file, and command line options?

The documentation seems to be quite sparse about it – the JSON configuration file isn't mentioned on the CLI documentation page, and https://jupyterlite.readthedocs.io/en/stable/howto/configure/config_files.html explains which JSON files affect the build command, but there is no reference about the priority as such. I think the priority is CLI > environment variables > JSON configuration file, but I need to check for the second and third comparisons.

2024-04-30 13:11 UTC, agriyakhetarpal commented
Or, we can not state the comparison directly through the sentence added in a9ca8867f44bd56bfa4a82c206e947bf2dedcb25, considering this is a feature for power users and they can figure out things as they try it (and no one would, in realistic contexts, use a mixture of all three: `conf.py`, environment variables, and a configuration JSON file altogether – a combination of the first and the third options is more likely).

This is ready for re-review/merging on my end.

2024-04-30 15:57 UTC, steppi commented on docs/configuration.md
> +This is an advanced feature and users are responsible for providing sensible command line options.
```suggestion
This is an advanced feature and users are responsible for providing sensible command line options.
The standard precedence between `jupyter lite build` CLI options and other means of configuration apply.
See the [jupyter lite CLI](https://jupyterlite.readthedocs.io/en/latest/reference/cli.html) documentation
for more info.
```

2024-04-30 16:07 UTC, steppi approved these changes

2024-04-30 16:09 UTC, steppi commented
Thanks @agriyakhetarpal, this looks good to me now.

2024-04-30 16:09 UTC, merged