Add a new-tabbed variant for the `Replite` directive, and allow customisation of button texts
jupyterlite/jupyterlite-sphinx pull request #228
Opened 2024-12-13 14:07 UTC by agriyakhetarpal

## Description

This continues #165, #223, and #227 for the Replite directive. We do not subclass from the `BaseNotebookTab` class here since we need to construct a URL with quoted code that has been passed to the directive (similar to the `TryExamples` directive).

I was initially unsure about doing this as I mentioned in https://github.com/jupyterlite/jupyterlite-sphinx/pull/227#issuecomment-2541405294, but the implementation seems to be in line enough with that for other directives and felt straightforward to me. This PR shall bring feature parity for all four major directives, and all five directives can now have new-tabbed variants. As a plus, customisation is allowed for this directive's new-tab button text as well, either by a global `replite_button_text` value or on a per-directive basis.

## Changes made

- A new `RepliteTab` class that inherits from `docutils.nodes.Element`. Here, we construct a URL for the REPL based on the input; and we return it when the `:new_tab:` option is enabled; otherwise, we return `RepliteIframe` instead.
- Documentation updated for the global `replite_button_text` option for `conf.py`, and a sample directive added to showcase Replite opening in a new tab.

2024-12-13 14:08 UTC, agriyakhetarpal commented
I've opened yet another PR today where your review would be appreciated, @Carreau 😁 Thanks a lot!

2024-12-20 19:45 UTC, steppi requested changes
Thanks Agriya. This ones looking good too. A suggestion about `"button_text"` and a couple minor suggestions.

2024-12-20 19:45 UTC, steppi commented on docs/directives/replite.md
> +If you use the `:new_tab:` option in the directive, the Replite console will be opened in a new browser tab
![image](https://github.com/user-attachments/assets/66782c87-4940-4999-beb6-4453928de404)

Something's going on in the docs here where the there's very little space between the replite iframe and this line of text.

2024-12-20 19:45 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +                button_text = self.env.config.replite_button_text
```suggestion
        if new_tab:
            directive_button_text = self.options.pop("button_text", None)
            if directive_button_text is not None:
                button_text = directive_button_text
            else:
                button_text = self.env.config.replite_button_text
            return [
                RepliteTab(
                    prefix=prefix,
                    width=width,
                    height=height,
                    prompt=prompt,
                    prompt_color=prompt_color,
                    content=content,
                    search_params=search_params,
                    lite_options=self.options,
                    button_text=button_text,
                )
            ]
```

It makes sense to put this here to avoid having to branch on `new_tab` again.

2024-12-20 19:45 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            )
Can we call this `"new_tab_button_text"` and just ignore it in `RepliteIframe`? Establishing this convention will also help us with `TryExamples` where the new tab button text isn't even configurable, but `button_text` is already used for the Try it button.

I saw you've established this same pattern elsewhere, in this file, but it looks like it hasn't made it into a release yet, so there's still time to change.

No one would be confused that `"new_tab_button_text"` doesn't control the prompt, so I think this would make things more clear. Also, in general, having options which are only allowed conditional on the value of other options is likely to create confusion.

2024-12-20 20:28 UTC, agriyakhetarpal commented on docs/directives/replite.md
> +If you use the `:new_tab:` option in the directive, the Replite console will be opened in a new browser tab
Yeah, I've noticed this problem before – I think this is the case for the NotebookLite and JupyterLite iframes as well. Should I attempt to fix it here or add a follow-up?

2024-12-20 20:36 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +                button_text = self.env.config.replite_button_text
Thanks – addressed in 2f96d85b6d259563ec6118dc0808f7ec234f356e.

2024-12-20 20:59 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            )
Yes, makes sense to modify the pattern everywhere, and +1 on not aiming to confuse people – I had the same thought!

I've renamed the option to `"new_tab_button_text"` for all three directives where applicable in 5d73efd0c653e1def463a84daaffeba48c5f2c37 and 874dbfd4cc0092f42eec83ff42e656222125973e, though I kept the variable name being passed as `button_text` internally, because the name of the class (`RepliteTab`) and its docstring (`"opens a REPL with JupyterLite in a new tab"`) inherently imply that the button text concerns a new tab.

Should I also rename the corresponding configuration options `jupyterlite_button_text` et al to `jupyterlite_new_tab_button_text`? I do feel that would be a bit long, but at the same time, I do get that it might instigate confusion on the difference between the prompt text and the button text (if one doesn't know what the iframes/buttons are supposed to represent visually).

2024-12-20 21:29 UTC, steppi commented on docs/directives/replite.md
> +If you use the `:new_tab:` option in the directive, the Replite console will be opened in a new browser tab
Follow up is fine

2024-12-20 21:37 UTC, steppi commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            )
Cool. Thanks Agriya. If `jupyterlite_button_text` and friends haven't made it into a release yet, I like `jupyterlite_new_tab_button_text` better, even though a little long. In the context  of writing a config file, it's not that much typing, and makes things more clear.

2024-12-20 21:41 UTC, agriyakhetarpal commented on docs/directives/replite.md
> +If you use the `:new_tab:` option in the directive, the Replite console will be opened in a new browser tab
Opened a new issue about it at #232, thanks!

2024-12-20 21:45 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            )
Sure – done in af260f6c0cb5bfbd74878432016f90629635feec. Yes, these options haven't made it to a release yet. Thanks for the correction.

2024-12-20 21:46 UTC, agriyakhetarpal commented on jupyterlite_sphinx/jupyterlite_sphinx.py
> +            )
Sure – done in af260f6c0cb5bfbd74878432016f90629635feec. Yes, these options haven't made it to a release yet. Thanks for the correction!

2024-12-20 21:47 UTC, agriyakhetarpal commented
Thanks for the review! I think I have addressed all points.

2024-12-20 22:19 UTC, steppi commented on docs/configuration.md
>  notebooklite_button_text = "My custom NotebookLite button text"
```suggestion
notebooklite_new_tab_button_text = "My custom NotebookLite button text"
```

Should this be changed too?

2024-12-20 22:32 UTC, agriyakhetarpal commented on docs/configuration.md
>  notebooklite_button_text = "My custom NotebookLite button text"
Oops, thanks! Addressed in 6a28fa4f6c5fe1a989fd0d47fdf1e714d8d0c8a8.

2024-12-20 23:22 UTC, steppi commented
For some reason the XPython kernel isn't being found in the readthedocs preview at https://jupyterlite-sphinx--228.org.readthedocs.build/en/228/. Closing and reopening to retrigger CI to see if it's a transient issue.

2024-12-20 23:25 UTC, agriyakhetarpal commented
That's a bit strange, I tried it on the PR preview (cleared cookies and cache as well) before you reran the build, and it seems to load fine for me:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0d9d1071-14b9-4d46-abc0-a658f68ed9fb" />

2024-12-20 23:28 UTC, steppi commented
It's strange yeah. I closed and reopened the markdown PR and the kernel is still found for me in the preview.

2024-12-21 03:28 UTC, steppi approved these changes
Looks good. Thanks @agriyakhetarpal. The issue with the docs was transient. I just didn't want to merge without trying out the docs.

2024-12-21 03:32 UTC, merged